branch-defaults:
  dev:
    environment: covid-amp-api-test
  master:
    environment: amp-test
    group_suffix: null
global:
  application_name: covid-amp-api
  branch: null
  default_ec2_keyname: vaccines_centos
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
