version: 2
jobs:
  deploy-prod:
    working_directory: ~/repo

    docker:
      - image: cimg/python:3.8

    steps:
      - checkout

      - run:
          name: Installing Deployment Dependencies
          working_directory: /
          command: |
            pip install awsebcli --upgrade

      - run:
          name: Deploying
          command: eb deploy covid-npi-policy-api-prod
  deploy-test:
    working_directory: ~/repo

    docker:
      - image: cimg/python:3.8

    steps:
      - checkout

      - run:
          name: Installing Deployment Dependencies
          working_directory: /
          command: |
            pip install awsebcli --upgrade

      - run:
          name: Deploying
          command: eb deploy covid-npi-policy-api-dev

workflows:
  version: 2
  build:
    jobs:
      - deploy-prod:
          filters:
            branches:
              only:
                - master
      - deploy-test:
          filters:
            branches:
              only:
                - dev-map-updates
                - dev
