version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  deploy:
    working_directory: ~/repo

    docker:
      - image: cimg/python:3.7.13

    parameters:
      env:
        type: string

    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Installing Deployment Dependencies
          working_directory: /
          command: |
            pip install awsebcli --upgrade

      - run:
          name: Deploying
          command: eb deploy <<parameters.env>>

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          env: "amp-prod2"
          filters:
            branches:
              only:
                - master
      - deploy:
          env: "amp-dev2-next"
          filters:
            branches:
              only:
                - dev
