version: 2.1
jobs:
  deploy:
    working_directory: ~/repo

    docker:
      - image: cimg/python:3.7

    parameters:
      env:
        type: string

    steps:
      - checkout

      - run:
          name: Installing Deployment Dependencies
          working_directory: /
          command: |
            pip install awsebcli --upgrade

      - run:
          name: Deploying
          command: eb deploy <<parameters.env>>

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          env: 'amp-prod'
          filters:
            branches:
              only:
                - master
      - deploy:
          env: 'amp-test'
          filters:
            branches:
              only:
                - dev
